apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: gang-test
  namespace: gang-demo
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 4  # 1 leader + 3 workers
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        schedulerName: volcano  # Use Volcano gang scheduler
        containers:
        - name: leader
          image: nginx:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          command: ["sleep", "3600"]
    workerTemplate:
      metadata:
        labels:
          role: worker
      spec:
        schedulerName: volcano  # Use Volcano gang scheduler
        containers:
        - name: worker
          image: nginx:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          command: ["sleep", "3600"]
