apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lws-volcano-podgroup-role
rules:
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - podgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - podgroups/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lws-volcano-podgroup-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lws-volcano-podgroup-role
subjects:
- kind: ServiceAccount
  name: lws-controller-manager
  namespace: lws-system
